### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by rsking**
this caught me as I couldn't work out why `propertychanged.remove_suffix` wasn't working

### CODE REVIEW

**Comment by canton7** [comment]
D'oh, good spot thanks!

**Comment by canton7** [comment]
I can rebase into develop if necessary - it's pulling in a lot of crud from master at the moment

**Comment by rsking** [comment]
Yeah, sorry for the crud from master, I didn't realize until after I'd created the PR

**Comment by canton7** [comment]
Thanks!

**Pull request merged**
